### ISSUE TITLE
Need to fix hack in group tests

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-ui#1224]
This PR is a hack: https://github.com/keycloak/keycloak-admin-ui/pull/1223

It fixes the group tests, but need to fix these two items:
https://github.com/keycloak/keycloak-admin-ui/pull/1223/files#diff-722625e870b781e1977dcc96f842cc5d438d21b7708239b8b52140544b2770fcR90-R92

https://github.com/keycloak/keycloak-admin-ui/pull/1223/files#diff-722625e870b781e1977dcc96f842cc5d438d21b7708239b8b52140544b2770fcR112-R114

**Comment by alevid99** [comment]
When you try to move a group to "root" in the modal you get a success message while the code crash e no update is performed.

Actually the button in the dialog the move button is enabled but when you click it nothing happen (you get a success message but you should get an error). On the confirmation callback the code crash (src/groups/GroupTable.tsx:214) the error get catch but due to the check src/groups/GroupTable.tsx:223 no error is raised.

@ssilvert the move to root action should be possible and the bug should be addressed?

**Comment by ssilvert** [comment]
@alevid99 Yes, move to root should be possible but I don't think it's working.

**Comment by ssilvert** [comment]
This is out of date as the test has been rewritten.  Also, I have confirmed that it now is possible to move a group to the root.
