### ISSUE TITLE
[UX Review] Optimize the help text of the Display name

### ISSUE THREAD

**Issue by xianli123** [keycloak/keycloak-ui#1599]
### Describe the bug

When creating a new resource, there is a field named "Display name". We can find that the tooltips of "Display name" and "Name" are the same. It's confusing. So we can optimize the wording of the "Display name" tooltip.
<img width="798" alt="Screen Shot 2021-11-24 at 11 23 57 AM" src="https://user-images.githubusercontent.com/53931519/143171752-7b0d9e0c-c5cf-4afe-be8e-b1695b71c945.png">
 

### Version

Admin new UI

**Comment by agagancarczyk** [comment]
hi @xianli123 could I ask you to help me with the new helpText for the DisplayName field? Thanks!

**Comment by xianli123** [comment]
Hi @stianst, could you please take a look at this issue? As for the tooltip of **Display name**, we want to change it to:
`A user-friendly name for the resource, mainly used when rendering user-facing forms. It supports internationalization so that values can be loaded from message bundles.` Does it make sense? Thanks!

**Comment by agagancarczyk** [comment]
hi @ssilvert are we in agreement with the new helpText proposed by @xianli123 `A user-friendly name for the resource, mainly used when rendering user-facing forms. It supports internationalization so that values can be loaded from message bundles`?  I can make this simple change once I get your ok. Thanks!

**Comment by ssilvert** [comment]
@agagancarczyk I like the text.  Go ahead.
