### ISSUE TITLE
Updating an executor in a client profile does not updates the value

### ISSUE THREAD

**Issue by Aboullos** [keycloak/keycloak-ui#2037]
### Describe the bug

Updating an executor in a client profile does not updates the value

### Version

16.1.0

### Expected behavior

The `Available Period` value gets updated

### Actual behavior

The `Available Period` stays the same

### How to Reproduce?

Create an executor in an Client profile, save and edit it with a different value

**Comment by Aboullos** [comment]
I was investigating a bit and the value gets updated, the request is sent correctly when the changes are saved and when the element is opened again it receives the correct information on a request. The only problem is that for the user is still showing the default values

**Comment by ikhomyn** [comment]
1. Go to Realm Settings -> Client policies -> Profiles tab
2. Create client profile -> type _Client profile name:_ **testPolicy** and Save.
3. On same Page, click Add executor -> Select **consent-required** and click Add
4. Update _Client profile name_ to any other and Save
5. Observe executors have disappeared.  It seems the reason is due to that they were fetched with previous old name.
6. Navigate Go to Realm Settings -> Client policies -> Profiles tab -> created policy details. Observe the executors are present.


Note: If you attempt to add first executor **confidential-client** : it will fail with err msg:  **Executor not created**
