### ISSUE TITLE
Username and email address changed after testing SMTP settings for another realm with "Email as username" enabled

### ISSUE THREAD

**Issue by lme-atolcd** [keycloak/keycloak-ui#3593]
### Describe the bug

When logged in with a user of the "Master" realm and testing SMTP settings for an other realm, both username and email of the logged in user are changed when "Email as username" is enabled for the other realm.

### Version

19.0.3

### Expected behavior

Username and email address of the logged in user are not changed.
The test email is sent.

### Actual behavior

Username and email address of the logged in user are both set to the email address used to test the SMTP settings.
No email are sent even though I clicked the "Test connection" button in the popup.

### How to Reproduce?

1. Start Keycloak 
  ```
  docker run -p 8080:8080 -e KEYCLOAK_ADMIN=admin -e KEYCLOAK_ADMIN_PASSWORD=admin quay.io/keycloak/keycloak:19.0.3 start-dev
  ```
2. log in the Keycloak admin console with the `admin` user
3. create a new realm
4. switch to this new realm
5. go to "Configure > Realm settings > Login" and enable "Email as username"
6. go to "Configure > Realm settings > Email" and configure the `From`, `Host` and `Port` fields
7. click "Save"
8. a popup appears and ask to provide an email address to test the SMTP settings
9. enter any email address and click "Test connection"
10. switch back to the "Master" realm
11. go to "Manage > Users"
12. both username and email address of the `admin` user are changed, both new values are the email address provided in the popup

**Comment by ssilvert** [comment]
Note that to see the pop-up described in step 8, you need to make sure the `admin` user does not have an email address set.

@jonkoops I have traced the bug to this PR: https://github.com/keycloak/keycloak-ui/pull/1325.  So I'm assigning to you for a fix.

The problem here is that the registration flow is setting username and email for the admin user.  Plus, the `master` realm might not be using `Email as user name`.  It looks like this flow should not happen at all as the admin user has not explicitly said he wants to make changes to his user profile.  

I'm not sure why this was necessary since the old console doesn't handle it this way.  But I don't deeply understand the original issue, so I'm hoping @jonkoops can sort it out.

**Comment by ssilvert** [comment]
BTW, the reason I set this as critical is because even though it's a weird corner case, it can result in an admin getting his user name changed without his knowledge.  Then he won't be able to log in.
