### ISSUE TITLE
New Admin UI allows multiple user-attributes with the same key

### ISSUE THREAD

**Issue by foliengriller** [keycloak/keycloak-ui#3904]
### Area

admin/ui

### Describe the bug

![image](https://user-images.githubusercontent.com/24498435/202702611-090b4052-c15f-4710-a362-3a2c6eaaae0e.png)

### Version

20.0.1

### Expected behavior

The key should be unique.

### Actual behavior

Key is used twice.

### How to Reproduce?

1. Create a User
2. add a first user-attribute with key "key" and some value
3. add a second user-attribute with key "key" and another value

### Anything else?

In to old UI the value just gets replaced without any warning / error. There should be a warning imho, that the key is already in use.

**Comment by ssilvert** [comment]
Thanks for the bug report.  Transferring to keycloak-ui repo.

**Comment by antikalk** [comment]
There seems to be an inconsistency between user and realm attributes on API level. While having a look at #3931 I noticed that the attributes for the user are returned as `string: string[]` whereas for the realm the are returned as `string: string`. Is there a reason for this difference and/or will this change in the future?

**Comment by jonkoops** [comment]
@edewit Didn't we re-work the attributes recently to resolve this issue?

**Comment by edewit** [comment]
This is not an issue, but an feature ;). In the old console in order to make a sting array you had to `value1##value2`, to get a `key` with 2 values. In the new one we allow to do this without the special characters and just put `key`, `value1` and `key`, `value2` instead. So no need to be aware of any special characters.

@antikalk on the server attributes are `string`, but on the frontend the can be `string[]`, afterwards they are "serialised" to string again

**Comment by jonkoops** [comment]
Ahhh, yeah. I was wondering if we ever implemented that design that @xianli123 made for handling this with multiple values for a single key, but I guess not.
